language: python
python:
    - 3.6
 
script:
    # remove original "zht"
    - rm -r localization/zht
    # copy "zht" into localization
    - cp -r zht/ localization/zht/
    # validation will check json format and compare json item with "eng"
    - python ./localization/validate_localization.py

notifications:
    email: false